#!/usr/bin/env python

'''
description:    Decode VOEvent db entry to xml: Runner
license:        APACHE 2.0
author:         Ronald van Haren, NLeSC (r.vanharen@esciencecenter.nl)
'''

import argparse
from pyAccess import decode_VOEvent as pAdecode

if __name__=="__main__":
    pAdecode.decode_FRBCat_entry()
