language: python
python:
  - "3.5"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
script:
  - nosetests tests/utils_test.py --with-coverage --cover-tests --cover-package=pyAccess
after_success:
  - bash <(curl -s https://codecov.io/bash)
